CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS salary;
CREATE SCHEMA IF NOT EXISTS community;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS identity.users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salary.submissions (
  id SERIAL PRIMARY KEY,
  job_title TEXT NOT NULL,
  company_name TEXT,
  years_of_experience INTEGER NOT NULL,
  base_salary DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'PENDING',
  created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS community.votes (
  id SERIAL PRIMARY KEY,
  submission_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  vote_type TEXT NOT NULL,
  created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(submission_id, user_id)
);
